[package]
name = "s1_zkp_for_dlog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3.3"
crypto-bigint = { version = "0.5.0-pre.3", features = ["generic-array"] }
